# Title: Makefile
# Abstract: This Makefiles compiles programming challenge 3.
# Author: Eamon Tracey
# Email: etracey@nd.edu
# Estimate: 10 minutes
# Date: 09/19/2022

all: dll-accounts dll-accounts-stretch

dll-accounts:
	gcc -Wall dll-accounts.c -o dll-accounts

dll-accounts-stretch:
	gcc -Wall dll-accounts-stretch.c -o dll-accounts-stretch

clean:
	rm dll-accounts dll-accounts-stretch