# Title: Makefile
# Abstract: The program compiles the programs for programming challenge 2.
# Author: Eamon Tracey
# Email: etracey@nd.edu
# Estimate: 10 mins
# Date: 09/06/20222

all: array-merge struct-array struct-search

array-merge:
	gcc -Wall array-merge.c -o array-merge

struct-array:
	gcc -Wall struct-array.c -o struct-array

struct-search:
	gcc -Wall struct-search.c -o struct-search

clean:
	rm array-merge struct-array struct-search
